spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api-gateway:8080/auth-service
          jwk-set-uri: http://auth-service:8081/oauth2/jwks

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: TRACE
    reactor.netty.http.client: TRACE
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
