spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: blog-service-route
              uri: lb://blog-service
              predicates:
                - Path=/api/blog/**
            - id: shopping-service-route
              uri: lb://shopping-service
              predicates:
                - Path=/api/shopping/**
            - id: auth-service-api
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
            - id: auth-service-route
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1