spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: blog-service-route
          uri: lb://blog-service
          predicates:
            - Path=/api/blog/**
        - id: shopping-service-route
          uri: lb://shopping-service
          predicates:
            - Path=/api/shopping/**
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**
            - Path=/oauth2/**
