eureka:
  instance:
    prefer-ip-address: false
    ip-address: 127.0.0.1
    hostName: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        # 기존에 health만 있었다면 env를 추가, 없었다면 그대로 추가
        include: "env,health"