spring:
  data:
    mongodb:
      uri: mongodb://laze:password@mongodb:27017/blog_db?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081
