spring:
  data:
    mongodb:
      uri: mongodb://laze:password@mongodb:27017/blog_db?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api-gateway:8080/auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always