# ===================================================================
# Discovery Service - Default Profile Configuration (for Local Env)
# ===================================================================

server:
  # Eureka 서버가 실행될 기본 포트
  port: 8761

spring:
  application:
    # Spring Cloud에서 서비스를 식별하기 위한 이름
    name: discovery-service

eureka:
  client:
    # false: Eureka 서버는 스스로를 클라이언트로 등록하지 않습니다.
    register-with-eureka: false
    # false: Eureka 서버는 다른 Eureka 서버로부터 레지스트리 정보를 가져오지 않습니다. (단일 서버 모드)
    # 클러스터 환경에서는 이 값을 true로 설정하여 다른 노드와 정보를 동기화합니다.
    fetch-registry: false