spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          timeout: 10

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.config: INFO
    org.springframework.boot.actuate: DEBUG