package com.portal.universe.authservice.auth.domain;

public enum AuditEventType {
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    PERMISSION_ADDED,
    PERMISSION_REMOVED,
    MEMBERSHIP_CREATED,
    MEMBERSHIP_UPGRADED,
    MEMBERSHIP_DOWNGRADED,
    MEMBERSHIP_EXPIRED,
    MEMBERSHIP_CANCELLED,
    MEMBERSHIP_RENEWED,
    SELLER_APPLICATION_SUBMITTED,
    SELLER_APPLICATION_APPROVED,
    SELLER_APPLICATION_REJECTED,
    TOKEN_REVOKED,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED
}
