---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: portal-universe
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: laze8771/portal-universe-config-service:latest
          command: ["java"]
          args: ["-jar", "app.jar"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 30   # 30초 후부터 체크
            periodSeconds: 10          # 10초마다 체크
            failureThreshold: 12       # 최대 12번 (총 2분)
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: portal-universe
  labels:
    app: config-service
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: config-service