apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Backend Services
  - api-gateway.yaml
  - auth-service.yaml
  - blog-service.yaml
  - shopping-service.yaml
  - shopping-seller-service.yaml
  - shopping-settlement-service.yaml
  - notification-service.yaml
  - drive-service.yaml
  - prism-service.yaml
  - chatbot-service.yaml

  # Frontend Apps
  - portal-shell.yaml
  - blog-frontend.yaml
  - shopping-frontend.yaml
  - shopping-seller-frontend.yaml
  - prism-frontend.yaml
  - admin-frontend.yaml
  - drive-frontend.yaml
