# ===================================================================
# Namespace 정의
# ===================================================================
apiVersion: v1
kind: Namespace
metadata:
  # 이 프로젝트의 모든 리소스가 생성될 네임스페이스의 이름입니다.
  name: portal-universe
  # 네임스페이스 자체에 레이블을 부여하여 식별 및 관리를 용이하게 합니다.
  labels:
    name: portal-universe
    environment: development
